server:
  port: 8001
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/tanha?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
